# Generated by Django 5.0.2 on 2024-03-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moder',
            name='post',
        ),
        migrations.AddField(
            model_name='moder',
            name='pex',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
