# Generated by Django 5.0.2 on 2024-03-02 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0002_remove_moder_post_moder_pex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_id', models.IntegerField()),
                ('username', models.CharField(max_length=12)),
                ('avatar', models.TextField()),
                ('global_name', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Pex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pex_name', models.CharField(max_length=12, verbose_name='pex')),
                ('display_name', models.CharField(max_length=12, verbose_name='display_name')),
                ('prefix_color', models.CharField(max_length=12, verbose_name='цвет префикса')),
                ('nickname_color', models.CharField(max_length=12, verbose_name='цвет ника')),
            ],
        ),
        migrations.AddField(
            model_name='moder',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='баланс'),
        ),
        migrations.AddField(
            model_name='moder',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='is_admin'),
        ),
        migrations.AlterField(
            model_name='moder',
            name='nickname',
            field=models.CharField(max_length=12, verbose_name='никнейм'),
        ),
        migrations.AddField(
            model_name='moder',
            name='discord',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='modtmrpg.discord'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moder',
            name='pex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modtmrpg.pex'),
        ),
    ]
