# Generated by Django 5.0.2 on 2024-03-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0003_discord_pex_moder_balance_moder_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pex',
            name='hierarchy',
            field=models.IntegerField(default=1, verbose_name='высота должности'),
        ),
    ]
