# Generated by Django 5.0.2 on 2024-03-02 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0004_pex_hierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moder',
            name='discord',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='modtmrpg.discord', unique=True),
        ),
        migrations.AlterField(
            model_name='moder',
            name='nickname',
            field=models.CharField(max_length=12, unique=True, verbose_name='никнейм'),
        ),
    ]
