# Generated by Django 5.0.2 on 2024-03-02 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0008_alter_discord_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moder',
            name='discord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modtmrpg.discord'),
        ),
    ]
