# Generated by Django 5.0.2 on 2024-03-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0016_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='note',
            field=models.TextField(default='Запрещена продажа и передача!', verbose_name='примечание'),
            preserve_default=False,
        ),
    ]
