# Generated by Django 5.0.2 on 2024-03-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0017_item_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
