# Generated by Django 5.0.2 on 2024-03-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0020_alter_moder_discord_alter_moder_pex'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_name', models.CharField(default='image', max_length=16, verbose_name='название')),
                ('media_file', models.ImageField(upload_to='items/')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
