# Generated by Django 5.0.2 on 2024-03-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0023_mediacategory_mediaitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacategory',
            name='category_folder',
            field=models.CharField(default='items', max_length=12, verbose_name='путь'),
            preserve_default=False,
        ),
    ]
