# Generated by Django 5.0.2 on 2024-03-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0025_alter_mediaitem_media_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='note',
            field=models.CharField(max_length=35, verbose_name='примечание'),
        ),
    ]
