# Generated by Django 5.0.2 on 2024-03-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0027_alter_item_description_alter_item_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=30, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=35, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='note',
            field=models.CharField(blank=True, max_length=35, verbose_name='примечание'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='media_name',
            field=models.CharField(max_length=30, verbose_name='название'),
        ),
    ]
