# Generated by Django 5.0.2 on 2024-03-04 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0028_alter_item_description_alter_item_item_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moder',
            name='is_admin',
        ),
    ]
