# Generated by Django 5.0.2 on 2024-03-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0029_remove_moder_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=31, verbose_name='название'),
        ),
    ]
