# Generated by Django 5.0.2 on 2024-03-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0031_item_image_url_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.TextField(blank=True, null=True, verbose_name='Путь либо ссылка на картинку'),
        ),
    ]
