# Generated by Django 5.0.2 on 2024-03-05 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0033_alter_moder_pex_alter_pex_pex_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moder',
            name='discord',
        ),
    ]
