# Generated by Django 5.0.2 on 2024-03-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0035_moder_discord'),
    ]

    operations = [
        migrations.AddField(
            model_name='moder',
            name='head_valid',
            field=models.BooleanField(default=False, verbose_name='Подгрузилась ли голова?'),
        ),
        migrations.AddField(
            model_name='moder',
            name='skin_valid',
            field=models.BooleanField(default=False, verbose_name='Подгрузился ли скин?'),
        ),
    ]
