# Generated by Django 5.0.2 on 2024-03-06 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0036_moder_head_valid_moder_skin_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='Количество')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modtmrpg.moder')),
            ],
        ),
    ]
