# Generated by Django 5.0.2 on 2024-03-06 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0037_ecolog'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecolog',
            name='moder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moder', to='modtmrpg.moder'),
        ),
        migrations.AlterField(
            model_name='ecolog',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='modtmrpg.moder'),
        ),
    ]
