# Generated by Django 5.0.2 on 2024-03-06 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0039_alter_ecolog_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecolog',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='modtmrpg.moder'),
        ),
    ]
