# Generated by Django 5.0.2 on 2024-03-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0040_alter_ecolog_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecolog',
            name='reason',
            field=models.CharField(default='', max_length=50, verbose_name='Причина'),
            preserve_default=False,
        ),
    ]
