# Generated by Django 5.0.2 on 2024-03-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0042_ecolog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecolog',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
