# Generated by Django 5.0.2 on 2024-03-06 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0043_alter_ecolog_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecolog',
            options={'ordering': ['date']},
        ),
    ]
