# Generated by Django 4.1.3 on 2024-03-07 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0045_alter_ecolog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discord',
            options={'verbose_name': 'Дискорд', 'verbose_name_plural': 'Дискорды'},
        ),
        migrations.AlterModelOptions(
            name='ecolog',
            options={'ordering': ['-date'], 'verbose_name': 'Лог экономики', 'verbose_name_plural': 'Логи экономики'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='mediacategory',
            options={'verbose_name': 'Категория медиа', 'verbose_name_plural': 'Категории медиа'},
        ),
        migrations.AlterModelOptions(
            name='mediaitem',
            options={'verbose_name': 'Предмет медиа', 'verbose_name_plural': 'Предметы медиа'},
        ),
        migrations.AlterModelOptions(
            name='moder',
            options={'verbose_name': 'Модератор', 'verbose_name_plural': 'Модераторы'},
        ),
        migrations.AlterModelOptions(
            name='pex',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='registerformmodel',
            options={'verbose_name': 'Регистрацционная форма', 'verbose_name_plural': 'Регистрационные формы'},
        ),
    ]
