# Generated by Django 4.1.3 on 2024-03-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0046_alter_discord_options_alter_ecolog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.TextField(blank=True, null=True, verbose_name='Путь либо ссылка на картинку (не трогай, если вставил картинкой)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.IntegerField(default=0, verbose_name='НЕ ТРОГАТЬ'),
        ),
    ]
