# Generated by Django 4.1.3 on 2024-03-08 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0047_alter_item_image_url_alter_item_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-type', 'price'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
    ]
