# Generated by Django 4.1.3 on 2024-03-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0048_alter_item_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-type', '-price'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
    ]
