# Generated by Django 4.1.3 on 2024-03-08 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0049_alter_item_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moder',
            options={'ordering': ['-pex__hierarchy'], 'verbose_name': 'Модератор', 'verbose_name_plural': 'Модераторы'},
        ),
    ]
