# Generated by Django 4.1.3 on 2024-03-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0050_alter_moder_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pex',
            name='display_name',
            field=models.CharField(max_length=15, verbose_name='display_name'),
        ),
    ]
