# Generated by Django 4.1.3 on 2024-03-10 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0051_alter_pex_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reprimand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50, verbose_name='Причина')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modtmrpg.Reprimand.admin+', to='modtmrpg.moder')),
                ('moder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modtmrpg.Reprimand.moder+', to='modtmrpg.moder')),
            ],
            options={
                'verbose_name': 'Выговор',
                'verbose_name_plural': 'Выговоры',
                'ordering': ['-date'],
            },
        ),
    ]
