# Generated by Django 4.1.3 on 2024-03-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0052_reprimand'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_auto',
            field=models.IntegerField(default=0, verbose_name='НЕ ТРОГАТЬ(auto)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.IntegerField(default=0, verbose_name='НЕ ТРОГАТЬ(type)'),
        ),
    ]
