# Generated by Django 4.1.3 on 2024-03-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0053_item_is_auto_alter_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecolog',
            name='reason',
            field=models.TextField(verbose_name='Причина'),
        ),
    ]
