# Generated by Django 4.1.3 on 2024-03-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0054_alter_ecolog_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reprimand',
            name='reason',
            field=models.TextField(verbose_name='Причина'),
        ),
    ]
