# Generated by Django 4.1.3 on 2024-04-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0060_alter_ecolog_admin_alter_ecolog_moder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(max_length=31, verbose_name='Название')),
                ('config', models.TextField(blank=True, verbose_name='Конфиг')),
            ],
            options={
                'verbose_name': 'Конфиг',
                'verbose_name_plural': 'Конфиги',
            },
        ),
        migrations.AddField(
            model_name='pex',
            name='OC_nickname_color',
            field=models.CharField(default='#383838', max_length=12, verbose_name='Цвет ника в компе'),
        ),
    ]
