# Generated by Django 4.1.3 on 2024-04-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0060_alter_ecolog_admin_alter_ecolog_moder'),
    ]

    operations = [
        migrations.AddField(
            model_name='pex',
            name='OC_nickname_color',
            field=models.CharField(default='#383838', max_length=12, verbose_name='Цвет ника в компе'),
            preserve_default=False,
        ),
    ]
