# Generated by Django 4.1.3 on 2024-04-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modtmrpg', '0063_alter_discord_global_name_alter_discord_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='description',
            field=models.TextField(blank=True, verbose_name='Заметки/описание'),
        ),
    ]
